# Generated by Django 5.1.1 on 2024-10-10 12:41

import ckeditor.fields
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('nombre', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('nombre', models.CharField(help_text='Nombre y Apellidos', max_length=200)),
                ('email', models.CharField(help_text='Correo electrónico', max_length=200)),
                ('telefono', models.CharField(blank=True, default='', help_text='Teléfono de contacto', max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, default='', help_text='Ciudad de residencia', max_length=100, null=True)),
                ('pais', models.CharField(blank=True, default='', help_text='País de residencia', max_length=100, null=True)),
                ('textoMensage', models.TextField(help_text='Mensage', max_length=10000)),
            ],
            options={
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('nosotros', ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Nosotros',
            },
        ),
        migrations.CreateModel(
            name='Campanas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('titulo', models.CharField(help_text='Título de la Campaña', max_length=200)),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True)),
                ('fecha_inicio_publicacion', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de inicio')),
                ('fecha_final_publicacion', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de finalización')),
                ('archivo_foto', models.FileField(blank=True, default='', null=True, upload_to='fotos/', verbose_name='Archivo Foto (1000x800 px)')),
                ('html', models.TextField(blank=True, default='', max_length=10000, null=True)),
                ('pdf', models.FileField(blank=True, default='', null=True, upload_to='pdf/', verbose_name='Archivo PDF')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('categoria', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='generales.categoria')),
            ],
            options={
                'verbose_name_plural': 'Campañas',
            },
        ),
    ]
