# Generated by Django 2.2.1 on 2022-03-10 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(upload_to='fotos/', verbose_name='Archivo con Foto del Usuario')),
                ('logo', models.FileField(upload_to='fotos/', verbose_name='Logo del Usuario')),
                ('nit', models.CharField(default='', max_length=30, verbose_name='NIT / CC #')),
                ('empresa', models.CharField(default='', max_length=100, verbose_name='Empresa')),
                ('direccion', models.CharField(default='', max_length=100, verbose_name='Direccion Comercial')),
                ('telefono', models.CharField(default='', max_length=100, verbose_name='Telefono Comercial')),
                ('email', models.CharField(default='', max_length=100, verbose_name='Telefono Comercial')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
