# Generated by Django 2.2.1 on 2023-03-08 17:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0002_auto_20230307_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('nosotros', ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Nosotros',
            },
        ),
        migrations.AlterField(
            model_name='campanas',
            name='archivo_foto',
            field=models.FileField(blank=True, default='', null=True, upload_to='fotos/', verbose_name='Archivo Foto (1000x800 px)'),
        ),
    ]
