# Generated by Django 5.1.1 on 2024-10-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0002_noticias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='imagen',
            field=models.FileField(default='', upload_to='imagenes/', verbose_name='Imagen (600 x 700px)'),
        ),
    ]
