# Generated by Django 3.2.7 on 2024-12-05 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0003_alter_noticias_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('cod_dane', models.CharField(default='', max_length=15, verbose_name='Codigo DANE del Departamento')),
                ('nombre', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Nombre del País')),
            ],
            options={
                'verbose_name_plural': 'Paises',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('latitude', models.FloatField(help_text='Latitude of the location, e.g., -34.603722', verbose_name='Latitude')),
                ('longitude', models.FloatField(help_text='Longitude of the location, e.g., -58.381592', verbose_name='Longitude')),
                ('name', models.CharField(help_text='Nombre del producto o Medio, e.j., Radio Ad.', max_length=200, verbose_name='Producto/Nombre Medio')),
                ('media_type', models.CharField(choices=[('Radio', 'Radio'), ('TV', 'Televisión'), ('Digital', 'Publicidad Digital'), ('BTL', 'Below the Line'), ('Print', 'Medios Impresos')], help_text='Tipo de Medio o Producto.', max_length=50, verbose_name='Tipo de Medio')),
                ('price', models.DecimalField(decimal_places=2, help_text='Pricio del Medio o Producto.', max_digits=10, verbose_name='Precio')),
                ('description', models.TextField(blank=True, help_text='Detalle descripción del medio o producto.', null=True, verbose_name='Descripción')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateField(auto_now_add=True, null=True)),
                ('modificado', models.DateField(auto_now=True, null=True)),
                ('cod_dane', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='COD-DANE')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Nombre del municipio/ciudad')),
                ('latitud', models.FloatField(help_text='Latitud de la localización, e.j., 4.63028', verbose_name='Latitud')),
                ('longitud', models.FloatField(help_text='Longitud de la localización, e.j., -74.4625', verbose_name='Longitud')),
                ('departamento', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='generales.departamento')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='generales.pais'),
        ),
    ]
