# Generated by Django 3.2.7 on 2024-12-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0005_productos_municipio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='description',
            new_name='descripción',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='price',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='media_type',
            new_name='tipo_de_medio',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='longitude',
        ),
        migrations.AddField(
            model_name='productos',
            name='latitud',
            field=models.FloatField(default=0, help_text='Latitud de localización, e.g., -34.603722', verbose_name='Latitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='longitud',
            field=models.FloatField(default=0, help_text='Longitude de localización, e.g., -58.381592', verbose_name='Longitud'),
            preserve_default=False,
        ),
    ]
