# Generated by Django 3.2.7 on 2024-12-05 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0006_auto_20241205_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
