# Generated by Django 3.2.7 on 2024-12-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0007_rename_descripción_productos_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='precio',
        ),
        migrations.AlterField(
            model_name='productos',
            name='longitud',
            field=models.FloatField(help_text='Longitud de localización, e.g., -58.381592', verbose_name='Longitud'),
        ),
    ]
