# Generated by Django 3.2.7 on 2024-12-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0008_auto_20241205_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='foto',
            field=models.FileField(blank=True, default='', upload_to='imagenes/productos/', verbose_name='Fotografía '),
        ),
        migrations.AddField(
            model_name='productos',
            name='url_streaming',
            field=models.URLField(blank=True, help_text='URL de streaming de audio o vídeo', max_length=300, null=True, verbose_name='URL Streaming'),
        ),
        migrations.AddField(
            model_name='productos',
            name='website',
            field=models.URLField(blank=True, help_text='URL sitio web del medio o producto', max_length=300, null=True, verbose_name='Sitio Web'),
        ),
    ]
