# Generated by Django 3.2.7 on 2024-12-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0009_auto_20241205_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='contacto',
            field=models.CharField(default=0, help_text='Nombre de la persona contacto del proveedor de medios', max_length=200, verbose_name='Nombre contacto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='direccion',
            field=models.CharField(default=0, help_text='Dirección comercial del proveedor de medios', max_length=200, verbose_name='Dirección comercial '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='email',
            field=models.EmailField(blank=True, help_text='Dirección de correo electrónico', max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='productos',
            name='telefono',
            field=models.CharField(default=0, help_text='Teléfono comercial del proveedor de medios', max_length=200, verbose_name='Teléfono comercial '),
            preserve_default=False,
        ),
    ]
