# Generated by Django 3.2.7 on 2024-12-06 12:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0011_alter_productos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=ckeditor.fields.RichTextField(default=0, help_text='Detalle descripción del medio o producto.', max_length=15000, verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productos',
            name='email',
            field=models.EmailField(default=0, help_text='Dirección de correo electrónico', max_length=254, verbose_name='Correo Electrónico'),
            preserve_default=False,
        ),
    ]
