# Generated by Django 3.2.7 on 2024-12-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0012_auto_20241206_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'ordering': ['municipio', 'nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='productos',
            name='tipo_de_medio',
            field=models.CharField(choices=[('Radio', 'Radio'), ('TV', 'Televisión'), ('Perifoneo', 'Perifoneo'), ('Digital', 'Publicidad Digital'), ('BTL', 'BTL - Below the Line'), ('Print', 'Medios Impresos'), ('Centros Comerciales', 'Centros Comerciales'), ('Lugares de alto tráfico', 'Lugares de alto tráfico')], help_text='Tipo de Medio o Producto.', max_length=50, verbose_name='Tipo de Medio'),
        ),
    ]
