# Generated by Django 3.2.7 on 2024-12-13 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0013_auto_20241211_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipios',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='municipio',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Municipios',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
